### ISSUE TITLE
US1: User Registration: As an unregistered user, I want to be able to register as a user with a chosen username and password to leverage/use services and information that are exclusively available to registered users

### ISSUE THREAD

**Issue by jonas-blum** [sopra-fs23-group-20/server#1]
### Acceptance Criteria
- [x] sopra-fs23-group-20/server#66
- [x] sopra-fs23-group-20/client#17
- [x] sopra-fs23-group-20/client#16
screen
- [x] sopra-fs23-group-20/server#69
