### ISSUE TITLE
US10: Scoreboard Display: As a player, I want to see a scoreboard displaying current points for each player in descending order after each round, followed by the start of the next round after 10 seconds.

### ISSUE THREAD

**Issue by robonder** [sopra-fs23-group-20/server#10]
### Acceptance Criteria
- [x] sopra-fs23-group-20/server#40
- [x] sopra-fs23-group-20/client#31
- [x] sopra-fs23-group-20/client#30
