### ISSUE TITLE
US12: User Settings: As a logged-in user, I want to view and edit my profile information, including username, password, and country of origin.

### ISSUE THREAD

**Issue by robonder** [sopra-fs23-group-20/server#12]
### Acceptance Criteria
- [ ] sopra-fs23-group-20/client#35
- [ ] sopra-fs23-group-20/client#34
- [ ] sopra-fs23-group-20/server#35

**Comment by dariomonopoli-dev** [comment]
41b4c204cbae6cb21c8b8da96fe7d22a8f8bd295
45f47f7724db9a67d931a67893886b249665733b
