### ISSUE TITLE
US2: User Login: As a registered user, I want to log in with my username and password to access exclusive services and information for registered users.

### ISSUE THREAD

**Issue by robonder** [sopra-fs23-group-20/server#2]
### Acceptance Criteria
- [ ] sopra-fs23-group-20/server#63
- [ ] sopra-fs23-group-20/client#19
- [ ] sopra-fs23-group-20/client#18
