### ISSUE TITLE
US6: Making a Guess: As a player, I want to guess the selected country in an input field, so that I can test my knowledge of countries and compare myself to the other players in my lobby.

### ISSUE THREAD

**Issue by robonder** [sopra-fs23-group-20/server#6]
### Acceptance Criteria
- [x] sopra-fs23-group-20/client#25
- [x] sopra-fs23-group-20/client#23
- [x] sopra-fs23-group-20/client#24
- [x] sopra-fs23-group-20/server#100
- [x] sopra-fs23-group-20/client#22
- [x] sopra-fs23-group-20/client#21
- [x] sopra-fs23-group-20/server#71 
- [x] sopra-fs23-group-20/server#72 
- [x] sopra-fs23-group-20/server#81
