### ISSUE TITLE
US7: Guessing Time Limit: As a player, I want a 30-second time limit to guess the current country during each round.

### ISSUE THREAD

**Issue by robonder** [sopra-fs23-group-20/server#7]
### Acceptance Criteria
- [x] sopra-fs23-group-20/server#48
- [x] sopra-fs23-group-20/client#26
- [x] sopra-fs23-group-20/server#50

**Comment by L-Huber** [comment]
all tasks are done
