### ISSUE TITLE
US8a: Textual Hints for Guessing a Country: As a player, I want to receive textual hints, such as population and capital to help me guess the current country when I am unable to guess it within 5 seconds.

### ISSUE THREAD

**Issue by dariomonopoli-dev** [sopra-fs23-group-20/server#77]
### Acceptance Criteria
- [x] sopra-fs23-group-20/server#84
- [x] sopra-fs23-group-20/client#8
- [x] sopra-fs23-group-20/server#101
