### ISSUE TITLE
US9: End of a Round: As a player, I want the current round to end automatically when everyone has submitted a guess or the 30-second time limit has been reached.

### ISSUE THREAD

**Issue by robonder** [sopra-fs23-group-20/server#9]
### Acceptance Criteria
- [x] sopra-fs23-group-20/server#42
- [x] sopra-fs23-group-20/server#43
- [x] sopra-fs23-group-20/client#29

**Comment by L-Huber** [comment]
all tasks done
